name: Deploy Laravel Backend

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "bootstrap/**"
      - "config/**"
      - "database/**"
      - "public/**"
      - "routes/**"
      - "storage/**"
      - "artisan"
      - "composer.*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      SSH_USER: ${{ secrets.SERVER_SSH_USER }}
      SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
      SSH_KEY:  ${{ secrets.SERVER_SSH_KEY }}
      REMOTE_PATH: ${{ secrets.SERVER_REMOTE_PATH }} # e.g. /var/www/api
      RESTART_CMD: ${{ secrets.SERVER_RESTART_CMD }} # e.g. sudo systemctl restart octane
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" | sed 's/\\n/\n/g' | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa >/dev/null || { echo "SSH key validation failed"; exit 1; }
          ssh-keyscan -p ${SSH_PORT:-22} "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Ensure remote directory
        run: |
          ssh -i ~/.ssh/id_rsa -p ${SSH_PORT:-22} ${SSH_USER}@${SSH_HOST} "mkdir -p ${REMOTE_PATH}"

      - name: Rsync code to server (no vendor/.env/storage)
        run: |
          rsync -az \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "vendor" \
            --exclude ".env" \
            --exclude "storage/" \
            -e "ssh -p ${SSH_PORT:-22} -i ~/.ssh/id_rsa" \
            ./ ${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}/

      - name: Install dependencies and migrate on server
        run: |
          ssh -i ~/.ssh/id_rsa -p ${SSH_PORT:-22} ${SSH_USER}@${SSH_HOST} "
            set -euo pipefail
            cd ${REMOTE_PATH}
            composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader --classmap-authoritative
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          "

      - name: Restart application
        if: env.RESTART_CMD != ''
        run: |
          ssh -i ~/.ssh/id_rsa -p ${SSH_PORT:-22} ${SSH_USER}@${SSH_HOST} "${RESTART_CMD}"
